app_archive_api:
    type: rest
    prefix: /admin/api
    resource: Manuxi\SuluArchiveBundle\Controller\Admin\ArchiveController
    name_prefix: sulu_archive.
    options:
        expose: true
sulu_archive_settings_api:
    type: rest
    prefix: /admin/api
    resource: Manuxi\SuluArchiveBundle\Controller\Admin\SettingsController
    name_prefix: sulu_archive.
    options:
        expose: true
