app_archives_api:
    resource: Manuxi\SuluArchiveBundle\Controller\Admin\ArchiveController
    type: attribute
    options:
        expose: true

app_archive_settings_api:
    resource: Manuxi\SuluArchiveBundle\Controller\Admin\SettingsController
    type: attribute
    options:
        expose: true
